### ISSUE TITLE
Add God Eater show data

### ISSUE THREAD

**Issue by Fyurie** [IanMitchell/Showtimes#22]
God Eater continues airing in around a month. The previous data should be added in soon, so we can use Deschtimes for 10-13.

**Comment by IanMitchell** [comment]
Lol good one

**Comment by Fyurie** [comment]
You think I'm kidding :')

**Comment by IanMitchell** [comment]
Wanna put money on it

**Comment by Fyurie** [comment]
hey Desch it's Saturday pls import

**Comment by IanMitchell** [comment]
Having issues with the import/export script; hopefully will have fixed today.

**Comment by IanMitchell** [comment]
Done
