### ISSUE TITLE
Improved .release Functionality

### ISSUE THREAD

**Issue by Fyurie** [IanMitchell/Showtimes#24]
Servrhe-style release mechanics are a fair ways off yet, but I had a semi-useful stop-gap idea come to mind.

Would it be possible to add another arg for a Nyaa torrent link (or torrent ID if that's easier)? This would make the syntax ".release [show] [link/id]".

This could the print a message to a specified channel (namely our public channel) when the command is run. Something along the lines of "[show] [ep number] released. You can download it at: [nyaa link]".

It's something I'd like to see the bot be able to do in the distant future as part of a release system, but this stop-gap would be nice for the short-and-mid-term.

**Comment by IanMitchell** [comment]
When you say Servrhe style release, do you mean where it uploads automatically?

**Comment by Fyurie** [comment]
Yeah, the full crazyness of finding files, combining, muxing, uploading etc.

**Comment by IanMitchell** [comment]
This issue belongs in ARX-7 - filing an issue there.
