### ISSUE TITLE
Use show titles so it doesn't break terribly like this

### ISSUE THREAD

**Issue by cheshyre** [IanMitchell/Showtimes#25]
![ss 2016-03-10 at 08 59 57](https://cloud.githubusercontent.com/assets/7194835/13691019/5cb766c2-e703-11e5-93ce-7b3d14332c83.png)

**Comment by IanMitchell** [comment]
Use aliases instead you mean? Hrm. I guess what I need to do (@fyurie) is add an "official" alias, and then several shorthand phrases that will help alleviate searching woes as well.

**Comment by Fyurie** [comment]
I could get behind that. One alias for all show outputs (AoKana, Erased, HaruChika, etc, as opposed to full and/or JP names), and a bunch of search terms, fuzzy or otherwise.

**Comment by IanMitchell** [comment]
Alright, I'll start planning that then. It won't be an easy change, unfortunately - it'll take some db work.

**Comment by IanMitchell** [comment]
Not needed on Discord
