### ISSUE TITLE
Support grouped nicks

### ISSUE THREAD

**Issue by cheshyre** [IanMitchell/Showtimes#30]
```
 <cheshyre> .done haifuri
 <Belfiore> Error: Unknown IRC nick. Ep 8 of Haifuri is at escro (last update 20 hours ago). [TL TLC ENC ED TM TS QC]
 * You are now known as Ephemere
 <Ephemere> .done haifuri
 <Belfiore> Updated Haifuri #8. Ep 8 of Haifuri is at escro (last update a few seconds ago). [TL TLC ENC ED TM TS QC]
```

**Comment by IanMitchell** [comment]
This is a drawback of the library I'm using on ARX-7, unfortunately. You could register each individual nick with the service, but that seems like a bit of a pain - preferable to this though?

**Comment by cheshyre** [comment]
Hm I'd have to look at it, but if you say that aliases aren't well supported then its fine. Is there no way to query the IRC server whether a specific nick is grouped with another nick?

**Comment by IanMitchell** [comment]
You could do it through Athena, but it'd be a little difficult to pull off - I'll look into it though

**Comment by tabaha** [comment]
you can do it with `/cs why #channel nick` to get the main nick as long as you have access on the channel

**Comment by IanMitchell** [comment]
Oh, hm. TIL

**Comment by IanMitchell** [comment]
This will take work on behalf of ARX-7, but gonna work on adding support for different nicks to the database

**Comment by IanMitchell** [comment]
Ok, multiple nicknames added. Rest on on ARX-7
